### ISSUE TITLE
Mod ID needs to be lowercase

### ISSUE THREAD

**Issue by Anubeia** [Falconjh/Empowered-Rails#2]
Unable to boot into Minecraft with this mod installed. Screenshot below.

<img width="470" alt="Issue" src="https://user-images.githubusercontent.com/52202062/140262458-caf6bb5e-5b1d-43c8-9e3f-aaf4c768b324.png">

**Comment by Falconjh** [comment]
Sorry about that renamed the project and I  guess I didn't check that. Just updated and rant to make sure it works on my machine; I'll have it updated here shortly and curseforge sometime after.

**Comment by Falconjh** [comment]
Should be fixed now.
